### ISSUE TITLE
Inconsistencies of hyphenation and diacritics

### ISSUE THREAD

**Issue by drgrigg** [alphgal/willa-cather_the-song-of-the-lark#2]
If you run `se find-mismatched-dashes .` you'll see a bunch of inconsistencies of hypenation, eg: chafing-dish and chafingdish.

Similarly if you run `se find-mismatched-diacritics .` you'll see inconsistencies of accents in words.

Please make all these consistent.

**Comment by alphgal** [comment]
Thanks David. I've fixed all the mismatched dashes except for titlepage/title-page. "titlepage" is used in the coding while "title-page" is used consistently within the text itself.

As for the diacritics, the inconsistencies are all due to the differences in usage between or within languages (e.g., "Pedró" is used in a Spanish song, but in the English text it's "Pedro" and "Kunst" is a different word to "künst-lich" in German). I would prefer to leave these as is as the usage per language is consistent.

**Comment by drgrigg** [comment]
OK
